config/routes.rb
Rails.application.routes.draw do
  resources :boozes
  devise_for :users
  root 'site#index'

  namespace :admin do
    get '/' => 'base#index'
  end
end

app/models/booze.rb
class Booze < ActiveRecord::Base
  belongs_to :user 
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  enum role: [:user, :admin]
  has_many :boozes
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < AdminController

  def index

  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_user_is_admin

  private

  def ensure_user_is_admin
    redirect_to root_path unless current_user && current_user.admin?
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
      devise_parameter_sanitizer.for(:account_update).concat([:name])
    end

end

app/controllers/boozes_controller.rb
class BoozesController < ApplicationController
  
  def index
    @boozes = Booze.all
  end

  def show
    @booze = Booze.find(params[:id])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
  end

end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boozes_helper.rb
module BoozesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/base/index.html.erb
<h1>Admin</h1>

app/views/boozes/index.html.erb
<h1>Booze</h1>
<% @boozes.each do |booze| %>
  <h2><%= link_to booze.name, booze_path(booze.id) %></h2>
<% end %>

app/views/boozes/show.html.erb
<h2>Description</h2>
<h4><%= @booze.category %></h4><br />
<h4><%= @booze.style %></h4><br />
<h4><%= @booze.brewery %></h4><br />
<h4><%= @booze.abv %></h4>
<%= link_to 'Previous Page', boozes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <%= link_to('Home', root_path, class: "btn btn-default btn-lg") %>
        <% if user_signed_in? %>
          <%= link_to('Edit Account', edit_user_registration_path, class: "btn btn-default btn-lg" )%>
          <%= link_to('Logout', destroy_user_session_path, class: "btn btn-default btn-lg", method: :delete) %>
        <% else %>
          <%= link_to('Sign Up', new_user_registration_path, class: "btn btn-default btn-lg") %>
          <%= link_to('Sign In', new_user_session_path, class: "btn btn-default btn-lg") %>
      <% end %>
    </div>
  </nav>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/site/index.html.erb
<div class="jumbotron">
  <h1>Home</h1>
</div>